import {actualDimensions} from '../constants/layout';

const windowWidth = actualDimensions.width;

export const styles: any = {
  base: {
    flexWrap: 'wrap',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    margin: 'auto',
    textAlign: 'center',
    width: '100%',
    // height: actualDimensions.height,
    paddingHorizontal: 20,
  },
  container: {
    display: 'flex',
    position: 'relative',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    maxWidth: '100%',
    height: actualDimensions.height,
    width: actualDimensions.width + 0.8,
    paddingHorizontal: 20,
  },
  commentsContainer: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    marginBottom: 10,
  },
  textSizes: {
    xs: {
      fontSize: 14,
      textAlign: 'center',
    },
    sm: {
      fontSize: 18,
      fontWeight: 'bold',
      textAlign: 'center',
    },
    md: {
      fontSize: 24,
      fontWeight: 'bold',
      textAlign: 'center',
    },
    lg: {
      fontSize: 30,
      fontWeight: 'bold',
      textAlign: 'center',
    },
  },
  image: {
    lg: {
      justifyContent: 'center',
      maxWidth: '100%',
      width: windowWidth,
      height: 300,
      resizeMode: 'center',
    },
    md: {
      justifyContent: 'center',
      maxWidth: '100%',
      width: windowWidth,
      height: 200,
      marginBottom: 8,
      borderRadius: 4,
      resizeMode: 'cover',
    },
  },
  card: {
    backgroundColor: 'white',
    borderRadius: 8,
    padding: 10,
    marginBottom: 20,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  input: {
    backgroundColor: 'white',
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderRadius: 5,
    borderColor: 'gray',
    maxWidth: '100%',
    width: windowWidth,
    height: 50,
    paddingHorizontal: 15,
  },
  button: {
    alignItems: 'center',
    marginTop: 4,
    justifyContent: 'center',
    width: '40%',
    height: 56,
    borderColor: 'gray',
    marginBottom: 10,
    padding: 20,
    borderRadius: 100,
    borderWidth: 1,
    alignSelf: 'center',
    backgroundColor: 'white',
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderRightWidth: 1,
  },
  closeButton: {
    position: 'absolute',
    top: 20,
    right: 20,
    zIndex: 1,
    textAlign: 'center',
    color: 'red',
    width: 40,
    height: 40,
    cursor: 'pointer',
    backgroundColor: 'white',
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderRadius: 5,
    borderColor: 'blue',
    fontSize: 40,
  },
  commentButton: {
    marginBottom: 5,
    gap: 10,
    marginHorizontal: 5,
    padding: 5,
    cursor: 'pointer',
    backgroundColor: 'white',
    borderTopWidth: 1,
    borderBottomWidth: 1,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderRadius: 5,
    borderColor: 'blue',
    fontSize: 40,
  },
  noCommentsText: {
    fontStyle: 'italic',
    color: 'gray',
  },
};
